---
- hosts: all
  gather_facts: false
  #ignore_errors: true 
  tasks: 
    - name: Check the date
      command: datefjggggghj
      ignore_errors: yes
    - name: check uptime
      command: uptime

